version: '3.8'

services:
  db:
    image: postgres:14.19
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${PORT}
    volumes:
      - ${DB_DATA}
      
volumes:
  db_data: